---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharath
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sharath
  template:
    metadata:
      labels:
        app: sharath
    spec:
      containers:
      - name: sharath
        image: sharath4444/tic-tac-toe:v1 #sharath4444/docker-project:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sharath-service
spec:
  selector:
    app: sharath
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
